//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_De_Cafeteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulo()
        {
            this.Facturacion_Articulos = new HashSet<Facturacion_Articulos>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int MarcaId { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public int ProveedorId { get; set; }
        public bool Existencia { get; set; }
        public bool Estado { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual Proveedore Proveedore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturacion_Articulos> Facturacion_Articulos { get; set; }
    }
}
