//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_De_Cafeteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cafeteria
    {
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public int ID_Campus { get; set; }
        public int Encargado { get; set; }
        public string Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Campu Campu { get; set; }
    }
}
