//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_De_Cafeteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Facturacion_Articulos = new HashSet<Facturacion_Articulos>();
            this.Cafeterias = new HashSet<Cafeteria>();
        }
    
        public int IdEMpleado { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public decimal Salario { get; set; }
        public string Cedula { get; set; }
        public string Tanda_labor { get; set; }
        public Nullable<int> Porciento_Comision { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturacion_Articulos> Facturacion_Articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cafeteria> Cafeterias { get; set; }
    }
}
