//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_De_Cafeteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        public int Matricula { get; set; }
        public string Nombre { get; set; }
        public string Carrera { get; set; }
        public string Colegio { get; set; }
    }
}
