//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_De_Cafeteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturacion_Articulos
    {
        public int Id { get; set; }
        public int EmpleadoId { get; set; }
        public int ArticuloId { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime Fecha_Venta { get; set; }
        public Nullable<decimal> Monto_De_Articulo { get; set; }
        public int Unidades_Vendidas { get; set; }
        public string Comentario { get; set; }
        public bool Estado { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
