//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_De_Cafeteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturacion_Articulos
    {
        public int Id { get; set; }
        public int EmpleadoId { get; set; }
        public int ArticuloId { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime Fecha_Venta { get; set; }
        public Nullable<decimal> Monto_De_Articulo { get; set; }
        public int Unidades_Vendidas { get; set; }
        public string Comentario { get; set; }
        public bool Estado { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
