//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_De_Cafeteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedore
    {
        public int IdProveedor { get; set; }
        public string NombreComercial { get; set; }
        public string RNC { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Estado { get; set; }
    }
}
