//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_De_Cafeteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        public int IdProveedor { get; set; }
        public string NombreComercial { get; set; }
        public string RNC { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Estado { get; set; }
    }
}
