//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_De_Cafeteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public int Cedula { get; set; }
        public string TipoUsuario { get; set; }
        public Nullable<decimal> LimiteCredito { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Estado { get; set; }
    }
}
